---
title: "asd_alignment"
author: "Author"
date: "2025-08-08"
output: html_document
---

```{r setup, include=FALSE}
pacman::p_load(
  buildmer,
  here,
  papaja,
  gghalves,
  tidyverse,
  ggplot2,
  fUnitRoots,
  bruceR,
  lmerTest,
  lme4,
  broom,
  patchwork,
  brms,
  BayesFactor,
  showtext,
  ggsci,
  ggalluvial,
  writexl,
  mclogit,
  ggbeeswarm,
  PsychWordVec
)
options(scipen = 9999, digits = 5)
```


```{r 评分}
files = fs::dir_ls("./new_Rating")
Rating.df <- purrr::map_dfr(files, readxl::read_xlsx) 

Rating.df.mean <- Rating.df |>
  dplyr::filter(Rating != "无产出" & Rating != "未产出") |>
  dplyr::mutate(Rating = as.numeric(Rating)) |>
  dplyr::filter(Rating >= 1 & Rating < 10)|>
  group_by(Rate_ID) |>
  summarise(Rating.mean = mean(Rating)) |>
  ungroup()|>
  as.data.frame()

#评分
asd_filtered <- Rating.df.mean |> filter(grepl("ASD", Rate_ID, ignore.case = TRUE))
asd_zh <- asd_filtered[grepl("zh$", asd_filtered$Rate_ID), ]
asd_ba <- asd_filtered[grepl("ba$", asd_filtered$Rate_ID), ]
asd_be <- asd_filtered[grepl("be$", asd_filtered$Rate_ID), ]
tdc_filtered <- Rating.df.mean |> filter(grepl("TDC", Rate_ID, ignore.case = TRUE))
tdc_zh <- tdc_filtered[grepl("zh$", tdc_filtered$Rate_ID), ]
tdc_ba <- tdc_filtered[grepl("ba$", tdc_filtered$Rate_ID), ]
tdc_be <- tdc_filtered[grepl("be$", tdc_filtered$Rate_ID), ]
pingfen <- rbind(asd_zh, asd_ba, asd_be, tdc_zh, tdc_ba, tdc_be)
```


```{r import data}
ASD <- rio::import("./data/ASD.xlsx")
TDC <- rio::import("./data/TDC.xlsx")
b1 <- rio::import("./data/Result1002.xlsx", which = "Block1")
b2 <- rio::import("./data/Result1002.xlsx", which = "Block2")
b3 <- rio::import("./data/Result1002.xlsx", which = "Block3")
basic <- rio::import("./data/Result1002.xlsx", which = "basic") %>% 
  filter(Child_name %in% c(ASD$Child_name, TDC$Child_name)) %>%
  mutate(AGE = scale(Age)[, 1],
         PPVTZ = scale(PPVT)[, 1])
df <- bind_rows(b1, b2, b3)

quxiang <- c("举起", "穿上", "摘下", "放下", "扔掉", "挂起","踢飞") 
jieguo <- c("关掉", "吃掉", "喝掉", "打破", "打碎", "关上",
            "拔掉", "摔坏", "洗净", "踩坏", "撕掉")

df01 <- df %>%
  dplyr::filter(Sen_ACC == 1, Syntax_production %in% c("ba", "zh", "be")) %>%
  merge(basic, by = "Child_name") %>%
  dplyr::mutate(Group = Group.x) %>%
  dplyr::select(-Group.x, -Group.y, -contains(".x"), -contains(".y"), -Task_Data, -Birth_data) %>%
  dplyr::select(Child_name, Sex, Age, Group, everything()) %>%
  dplyr::filter(Words_prime %in% c(quxiang, jieguo)) %>%
  dplyr::mutate(词类 = ifelse(Words_prime %in% quxiang, "趋向动补", "结果动补"),
                词类 = factor(词类, levels = c("趋向动补", "结果动补"))) |>
  dplyr::mutate(Syntax_production = factor(Syntax_production, levels = c("zh", "ba", "be")),
                Trials = factor(Trials),
                Child_name = factor(Child_name),
                Group = factor(Group, levels = c("TDC", "ASD")),
                Syntax_prime = factor(Syntax_prime, levels = c("zh", "ba", "be")))
df01 <- merge(df01, pingfen, by = "Rate_ID")
```


```{r 把数据整理和模型}
dfba <- df01 |> 
  dplyr::filter(Syntax_prime != "be") %>%
  dplyr::mutate(Syntax_production = factor(Syntax_production, levels = c("zh", "ba", "be")),
                Trials = factor(Trials),
                Child_name = factor(Child_name),
                Group = factor(Group, levels = c("TDC", "ASD")),
                Syntax_align = ifelse(Syntax_production == "ba", 1, 0))

models_ba <- list(
  pf1 = Syntax_align ~ 1 + Syntax_prime * Group * 词类 + PPVTZ + (1| Child_name) + (1 | Trials),
  pf2 = Syntax_align ~ 1 + Syntax_prime * Group * 词类 + PPVTZ + (1| Trials),
  pf3 = Syntax_align ~ 1 + Syntax_prime * Group * 词类 + (1| Child_name),
  pf4 = Syntax_align ~ 1 + Syntax_prime * Group * 词类 + PPVTZ,
  pf5 = Syntax_align ~ 1 + Syntax_prime * Group * 词类 + (1| Trials) +(1| Child_name),
  pf6 = Syntax_align ~ 1 + Syntax_prime * Group * 词类 + (1| Trials),
  pf7 = Syntax_align ~ 1 + Syntax_prime * Group * 词类+ (1| Child_name),
  pf8 = Syntax_align ~ 1 + Syntax_prime * Group * 词类,
  pf9 = Syntax_align ~ 1 + Syntax_prime * Group + 词类 + PPVTZ + (1| Child_name) + (1 | Trials),
  pf10 = Syntax_align ~ 1 + Syntax_prime * Group + 词类 + PPVTZ + (1| Trials),
  pf11 = Syntax_align ~ 1 + Syntax_prime * Group + 词类 + (1| Child_name),
  pf12 = Syntax_align ~ 1 + Syntax_prime * Group + 词类 + PPVTZ,
  pf13 = Syntax_align ~ 1 + Syntax_prime * Group + 词类 + (1| Trials) +(1| Child_name),
  pf14 = Syntax_align ~ 1 + Syntax_prime * Group + 词类 + (1| Trials),
  pf15 = Syntax_align ~ 1 + Syntax_prime * Group + 词类+ (1| Child_name),
  pf16 = Syntax_align ~ 1 + Syntax_prime * Group + 词类,
  pf17 = Syntax_align ~ 1 + Syntax_prime + Group + 词类 + PPVTZ + (1| Child_name) + (1 | Trials),
  pf18 = Syntax_align ~ 1 + Syntax_prime + Group + 词类 + PPVTZ + (1| Trials),
  pf19 = Syntax_align ~ 1 + Syntax_prime + Group + 词类 + (1| Child_name),
  pf20 = Syntax_align ~ 1 + Syntax_prime + Group + 词类 + PPVTZ,
  pf21 = Syntax_align ~ 1 + Syntax_prime + Group + 词类 + (1| Trials) +(1| Child_name),
  pf22 = Syntax_align ~ 1 + Syntax_prime + Group + 词类 + (1| Trials),
  pf23 = Syntax_align ~ 1 + Syntax_prime + Group + 词类+ (1| Child_name),
  pf24 = Syntax_align ~ 1 + Syntax_prime + Group + 词类
 ) 
```

```{r 把模型建立和比较}
ba_objects <- list()
ba_summaries <- list ()
for (model_name in names(models_ba)) {
  formula <- models_ba[[model_name]]
  model <- brm(
    formula = formula,
    data = dfba ,
    family = bernoulli(link = "logit"),
    init = 0,
    chains = 4,
    warmup = 1000,
    iter = 5000,
    thin = 1,
    cores = 4)

  ba_objects[[model_name]] <- model
  ba_summaries[[model_name]] <- summary(model)
}
```

```{r 把模型比较}
set.seed(0331)
loo_ba <- list()
for (model_name in names(ba_objects)) {
  loo_ba[[model_name]] <- LOO(ba_objects[[model_name]])
}
ba.compare <- brms::LOO(
  ba_objects$pf1,
  ba_objects$pf2,
  ba_objects$pf3,
  ba_objects$pf4,
  ba_objects$pf5,
  ba_objects$pf6,
  ba_objects$pf7,
  ba_objects$pf8,
  ba_objects$pf9,
  ba_objects$pf10,
  ba_objects$pf11,
  ba_objects$pf12,
  ba_objects$pf13,
  ba_objects$pf14,
  ba_objects$pf15,
  ba_objects$pf16,
  ba_objects$pf17,
  ba_objects$pf18,
  ba_objects$pf19,
  ba_objects$pf20,
  ba_objects$pf21,
  ba_objects$pf22,
  ba_objects$pf23,
  ba_objects$pf24
)

ba1.mae <- posterior_predict(ba_objects$pf1)
ba2.mae <- posterior_predict(ba_objects$pf2)
ba3.mae <- posterior_predict(ba_objects$pf3)
ba4.mae <- posterior_predict(ba_objects$pf4)
ba5.mae <- posterior_predict(ba_objects$pf5)
ba6.mae <- posterior_predict(ba_objects$pf6)
ba7.mae <- posterior_predict(ba_objects$pf7)
ba8.mae <- posterior_predict(ba_objects$pf8)
ba9.mae <- posterior_predict(ba_objects$pf9)
ba10.mae <- posterior_predict(ba_objects$pf10)
ba11.mae <- posterior_predict(ba_objects$pf11)
ba12.mae <- posterior_predict(ba_objects$pf12)
ba13.mae <- posterior_predict(ba_objects$pf13)
ba14.mae <- posterior_predict(ba_objects$pf14)
ba15.mae <- posterior_predict(ba_objects$pf15)
ba16.mae <- posterior_predict(ba_objects$pf16)
ba17.mae <- posterior_predict(ba_objects$pf17)
ba18.mae <- posterior_predict(ba_objects$pf18)
ba19.mae <- posterior_predict(ba_objects$pf19)
ba20.mae <- posterior_predict(ba_objects$pf20)
ba21.mae <- posterior_predict(ba_objects$pf21)
ba22.mae <- posterior_predict(ba_objects$pf22)
ba23.mae <- posterior_predict(ba_objects$pf23)
ba24.mae <- posterior_predict(ba_objects$pf24)

ba1 <- median(abs(apply(ba1.mae, 2, mean) - dfba[, 28]))
ba2 <- median(abs(apply(ba2.mae, 2, mean) - dfba[, 28]))
ba3 <- median(abs(apply(ba3.mae, 2, mean) - dfba[, 28]))
ba4 <- median(abs(apply(ba4.mae, 2, mean) - dfba[, 28]))
ba5 <- median(abs(apply(ba5.mae, 2, mean) - dfba[, 28]))
ba6 <- median(abs(apply(ba6.mae, 2, mean) - dfba[, 28]))
ba7 <- median(abs(apply(ba7.mae, 2, mean) - dfba[, 28]))
ba8 <- median(abs(apply(ba8.mae, 2, mean) - dfba[, 28]))
ba9 <- median(abs(apply(ba9.mae, 2, mean) - dfba[, 28]))
ba10 <- median(abs(apply(ba10.mae, 2, mean) - dfba[, 28]))
ba11 <- median(abs(apply(ba11.mae, 2, mean) - dfba[, 28]))
ba12 <- median(abs(apply(ba12.mae, 2, mean) - dfba[, 28]))
ba13 <- median(abs(apply(ba13.mae, 2, mean) - dfba[, 28]))
ba14 <- median(abs(apply(ba14.mae, 2, mean) - dfba[, 28]))
ba15 <- median(abs(apply(ba15.mae, 2, mean) - dfba[, 28]))
ba16 <- median(abs(apply(ba16.mae, 2, mean) - dfba[, 28]))
ba17 <- median(abs(apply(ba17.mae, 2, mean) - dfba[, 28]))
ba18 <- median(abs(apply(ba18.mae, 2, mean) - dfba[, 28]))
ba19 <- median(abs(apply(ba19.mae, 2, mean) - dfba[, 28]))
ba20 <- median(abs(apply(ba20.mae, 2, mean) - dfba[, 28]))
ba21 <- median(abs(apply(ba21.mae, 2, mean) - dfba[, 28]))
ba22 <- median(abs(apply(ba22.mae, 2, mean) - dfba[, 28]))
ba23 <- median(abs(apply(ba23.mae, 2, mean) - dfba[, 28]))
ba24 <- median(abs(apply(ba24.mae, 2, mean) - dfba[, 28]))
bayestestR::hdi(ba_objects$pf21)
```
动趋式+TD+主动句logit(p) =-1.81+0+0+0, p = 1/(1+exp(-(-1.81))) = 0.14
动趋式+TD+把字句logit(p)=−1.81+2.59=0.78, p =  1/(1+exp(-0.78)) = 0.68
动结式+TD+主动句logit(p)=−1.81+0.91=−0.90, p = 1/(1+exp(-(-0.90))) = 0.29
动结式+TD+把字句logit(p)=−1.81+2.59+0.91=1.69, p = 1/(1+exp(-1.69)) =0.84
动趋式+ASD+主动句logit(p) =-1.81+0+0+0, p = 1/(1+exp(-(-1.81))) = 0.85
动趋式+ASD+把字句logit(p)=−1.81+2.59=0.78, p =  1/(1+exp(-0.78)) = 0.31
动结式+ASD+主动句logit(p)=−1.81+0.91=−0.90, p = 1/(1+exp(-(-0.90))) = 0.71
动结式+ASD+把字句logit(p)=−1.81+2.59+0.91=1.69, p = 1/(1+exp(-1.69)) =0.15

```{r 把模型拟合}
ba21_trace <- bayesplot::mcmc_trace(ba_objects$pf21,
                                    pars = c("b_Syntax_primeba",
                                             "b_GroupASD",
                                             "b_词类结果动补")) +
  theme(legend.text = element_text(size = 8),
        legend.title = element_text(size = 10),
        legend.margin = margin(1, 1, 1, 1, "pt"),
        legend.key.size = unit(1, "lines"),
        legend.key.height = unit(1, "lines")) +
  guides(color = guide_legend(override.aes = list(size = 0.5)))
ba21_trace
ggsave(plot = ba21_trace, "./figure/ba21_trace.svg", width = 10, height = 4)

ba21.ppcheck <- pp_check(ba_objects$pf21, ndraws = 100)
ba21.ppcheck 
ba21.b <- mcmc_plot(ba_objects$pf21, 
                    variable = c("b_Syntax_primeba", 
                                 "b_GroupASD", 
                                 "b_词类结果动补"),
                    type = "areas", prob = 0.95)
ba21.b
ba21.pos <- posterior_predict(ba_objects$pf21)
ba21.hdi <- bayestestR::hdi(ba_objects$pf21)
dfba$predict = predict(ba_objects$pf21, type = "response")[, 1]
```


```{r 被数据整理和模型}
dfbe <- df01 |> 
  dplyr::filter(Syntax_prime != "ba") %>%
  dplyr::mutate(Syntax_production = factor(Syntax_production, levels = c("zh", "ba", "be")),
                Trials = factor(Trials),
                Child_name = factor(Child_name),
                Group = factor(Group, levels = c("TDC", "ASD")),
                Syntax_align = ifelse(Syntax_production == "be", 1, 0))

models_be <- list(
  pf1 = Syntax_align ~ 1 + Syntax_prime * Group * 词类 + PPVTZ + (1| Child_name) + (1 | Trials),
  pf2 = Syntax_align ~ 1 + Syntax_prime * Group * 词类 + PPVTZ + (1| Trials),
  pf3 = Syntax_align ~ 1 + Syntax_prime * Group * 词类 + (1| Child_name),
  pf4 = Syntax_align ~ 1 + Syntax_prime * Group * 词类 + PPVTZ,
  pf5 = Syntax_align ~ 1 + Syntax_prime * Group * 词类 + (1| Trials) +(1| Child_name),
  pf6 = Syntax_align ~ 1 + Syntax_prime * Group * 词类 + (1| Trials),
  pf7 = Syntax_align ~ 1 + Syntax_prime * Group * 词类+ (1| Child_name),
  pf8 = Syntax_align ~ 1 + Syntax_prime * Group * 词类,
  pf9 = Syntax_align ~ 1 + Syntax_prime * Group + 词类 + PPVTZ + (1| Child_name) + (1 | Trials),
  pf10 = Syntax_align ~ 1 + Syntax_prime * Group + 词类 + PPVTZ + (1| Trials),
  pf11 = Syntax_align ~ 1 + Syntax_prime * Group + 词类 + (1| Child_name),
  pf12 = Syntax_align ~ 1 + Syntax_prime * Group + 词类 + PPVTZ,
  pf13 = Syntax_align ~ 1 + Syntax_prime * Group + 词类 + (1| Trials) +(1| Child_name),
  pf14 = Syntax_align ~ 1 + Syntax_prime * Group + 词类 + (1| Trials),
  pf15 = Syntax_align ~ 1 + Syntax_prime * Group + 词类+ (1| Child_name),
  pf16 = Syntax_align ~ 1 + Syntax_prime * Group + 词类,
  pf17 = Syntax_align ~ 1 + Syntax_prime + Group + 词类 + PPVTZ + (1| Child_name) + (1 | Trials),
  pf18 = Syntax_align ~ 1 + Syntax_prime + Group + 词类 + PPVTZ + (1| Trials),
  pf19 = Syntax_align ~ 1 + Syntax_prime + Group + 词类 + (1| Child_name),
  pf20 = Syntax_align ~ 1 + Syntax_prime + Group + 词类 + PPVTZ,
  pf21 = Syntax_align ~ 1 + Syntax_prime + Group + 词类 + (1| Trials) +(1| Child_name),
  pf22 = Syntax_align ~ 1 + Syntax_prime + Group + 词类 + (1| Trials),
  pf23 = Syntax_align ~ 1 + Syntax_prime + Group + 词类+ (1| Child_name),
  pf24 = Syntax_align ~ 1 + Syntax_prime + Group + 词类
 ) 
```


```{r 被模型建立和比较}
set.seed(0331)
be_objects <- list()
be_summaries <- list ()
for (model_name in names(models_be)) {
  formula <- models_be[[model_name]]
  model <- brm(
    formula = formula,
    data = dfbe,
    family = bernoulli(link = "logit"),
    init = 0,
    chains = 4,
    warmup = 1000,
    iter = 5000,
    thin = 1,
    cores = 4)

  be_objects[[model_name]] <- model
  be_summaries[[model_name]] <- summary(model)
}
```

```{r 被模型比较}
loo_be <- list()
for (model_name in names(be_objects)) {
  loo_be[[model_name]] <- LOO(be_objects[[model_name]])
}
be.compare <- brms::LOO(
  be_objects$pf1,
  be_objects$pf2,
  be_objects$pf3,
  be_objects$pf4,
  be_objects$pf5,
  be_objects$pf6,
  be_objects$pf7,
  be_objects$pf8,
  be_objects$pf9,
  be_objects$pf10,
  be_objects$pf11,
  be_objects$pf12,
  be_objects$pf13,
  be_objects$pf14,
  be_objects$pf15,
  be_objects$pf16,
  be_objects$pf17,
  be_objects$pf18,
  be_objects$pf19,
  be_objects$pf20,
  be_objects$pf21,
  be_objects$pf22,
  be_objects$pf23,
  be_objects$pf24
)

be1.mae <- posterior_predict(be_objects$pf1)
be2.mae <- posterior_predict(be_objects$pf2)
be3.mae <- posterior_predict(be_objects$pf3)
be4.mae <- posterior_predict(be_objects$pf4)
be5.mae <- posterior_predict(be_objects$pf5)
be6.mae <- posterior_predict(be_objects$pf6)
be7.mae <- posterior_predict(be_objects$pf7)
be8.mae <- posterior_predict(be_objects$pf8)
be9.mae <- posterior_predict(be_objects$pf9)
be10.mae <- posterior_predict(be_objects$pf10)
be11.mae <- posterior_predict(be_objects$pf11)
be12.mae <- posterior_predict(be_objects$pf12)
be13.mae <- posterior_predict(be_objects$pf13)
be14.mae <- posterior_predict(be_objects$pf14)
be15.mae <- posterior_predict(be_objects$pf15)
be16.mae <- posterior_predict(be_objects$pf16)
be17.mae <- posterior_predict(be_objects$pf17)
be18.mae <- posterior_predict(be_objects$pf18)
be19.mae <- posterior_predict(be_objects$pf19)
be20.mae <- posterior_predict(be_objects$pf20)
be21.mae <- posterior_predict(be_objects$pf21)
be22.mae <- posterior_predict(be_objects$pf22)
be23.mae <- posterior_predict(be_objects$pf23)
be24.mae <- posterior_predict(be_objects$pf24)

be1 <- median(abs(apply(be1.mae, 2, mean) - dfbe[, 28]))
be2 <- median(abs(apply(be2.mae, 2, mean) - dfbe[, 28]))
be3 <- median(abs(apply(be3.mae, 2, mean) - dfbe[, 28]))
be4 <- median(abs(apply(be4.mae, 2, mean) - dfbe[, 28]))
be5 <- median(abs(apply(be5.mae, 2, mean) - dfbe[, 28]))
be6 <- median(abs(apply(be6.mae, 2, mean) - dfbe[, 28]))
be7 <- median(abs(apply(be7.mae, 2, mean) - dfbe[, 28]))
be8 <- median(abs(apply(be8.mae, 2, mean) - dfbe[, 28]))
be9 <- median(abs(apply(be9.mae, 2, mean) - dfbe[, 28]))
be10 <- median(abs(apply(be10.mae, 2, mean) - dfbe[, 28]))
be11 <- median(abs(apply(be11.mae, 2, mean) - dfbe[, 28]))
be12 <- median(abs(apply(be12.mae, 2, mean) - dfbe[, 28]))
be13 <- median(abs(apply(be13.mae, 2, mean) - dfbe[, 28]))
be14 <- median(abs(apply(be14.mae, 2, mean) - dfbe[, 28]))
be15 <- median(abs(apply(be15.mae, 2, mean) - dfbe[, 28]))
be16 <- median(abs(apply(be16.mae, 2, mean) - dfbe[, 28]))
be17 <- median(abs(apply(be17.mae, 2, mean) - dfbe[, 28]))
be18 <- median(abs(apply(be18.mae, 2, mean) - dfbe[, 28]))
be19 <- median(abs(apply(be19.mae, 2, mean) - dfbe[, 28]))
be20 <- median(abs(apply(be20.mae, 2, mean) - dfbe[, 28]))
be21 <- median(abs(apply(be21.mae, 2, mean) - dfbe[, 28]))
be22 <- median(abs(apply(be22.mae, 2, mean) - dfbe[, 28]))
be23 <- median(abs(apply(be23.mae, 2, mean) - dfbe[, 28]))
be24 <- median(abs(apply(be24.mae, 2, mean) - dfbe[, 28]))
bayestestR::hdi(be_objects$pf9)
```

动趋式+TD+主动句logit(p) =-20.08+0+0+0, p = 1/(1+exp(-(-20.08))) = 0
动趋式+TD+被字句logit(p)=-20.08+18.11+0+0+0=-2.72, p =  1/(1+exp(-0.78)) = 6.16%
动结式+TD+主动句logit(p)=−20.83+0+0+0.29+0=−20.54, p = 1/(1+exp(-(−20.54))) = 0
动结式+TD+被字句logit(p)=−20.83+18.11+0+0.29+0=−2.43, p = 1/(1+exp(-2.43)) =0.08
动趋式+ASD+主动句logit(p) =−20.83+0+14.16+0+0=−6.67, p = 1/(1+exp(-(-6.67))) = 0.13
动趋式+ASD+被字句logit(p)=−−20.83+18.11+14.16+0+(−12.64)=−1.20, p =  1/(1+exp(1.2)) = 23.1%
动结式+ASD+主动句logit(p)=−20.83+0+14.16+0.29+0, p = 1/(1+exp(6.38)) =0.17%
动结式+ASD+被字句logit(p)=−20.83+18.11+14.16+0.29+(−12.64)=−0.91，p = 1/(1+exp(0.91 )) =28.7%


```{r 被模型拟合}
be19_trace <- bayesplot::mcmc_trace(be_objects$pf19,
                                    pars = c("b_Syntax_primebe",
                                             "b_GroupASD",
                                             "b_词类结果动补")) +
  theme(legend.text = element_text(size = 8),
        legend.title = element_text(size = 10),
        legend.margin = margin(1, 1, 1, 1, "pt"),
        legend.key.size = unit(1, "lines"),
        legend.key.height = unit(1, "lines")) +
  guides(color = guide_legend(override.aes = list(size = 0.5)))
be19_trace
ggsave(plot = be19_trace, "./figure/be19_trace.svg", width = 10, height = 4)

be19.ppcheck <- pp_check(be_objects$pf19, ndraws = 100)
be19.ppcheck 
be19.b <- mcmc_plot(be_objects$pf19, 
                    variable = c("b_Syntax_primebe", 
                                 "b_GroupASD", 
                                 "b_词类结果动补"),
                    type = "areas", prob = 0.95)
be19.b
be19.pos <- posterior_predict(be_objects$pf19)
be19.hdi <- bayestestR::hdi(be_objects$pf19)
dfbe$predict = predict(be_objects$pf19, type = "response")[, 1]
```

```{r 主动句把字句数据整理}
dfba0 <- dfba |>
  group_by(Child_name, Group, Syntax_prime) |>
  summarise(可能性 = mean(Syntax_align)) |>
  ungroup() |>
  as.data.frame() |>
  rename(组别 = Group, 句法结构 = "Syntax_prime")
dfbe0 <- dfbe |>
  group_by(Child_name, Group, Syntax_prime) |>
  summarise(可能性 = mean(Syntax_align)) |>
  ungroup() |>
  as.data.frame() |>
  rename(组别 = Group, 句法结构 = "Syntax_prime")
```

```{r 把字句主动句画图}
dfba2 <- dfba0 %>% mutate(x_pos = case_when(句法结构 == "ba" ~ 1, 句法结构 == "zh" ~ 2))
df_unique <- dfba2 %>%distinct(Child_name, 组别, 句法结构, 可能性, .keep_all = TRUE)

ba_summary <- df_unique %>%
  group_by(组别, 句法结构, x_pos) %>%
  summarise(
    均值 = mean(可能性),
    标准差 = sd(可能性),
    n = n(),
    标准误 = 标准差 / sqrt(n),
    CI_lower = 均值 - 1.96 * 标准误,
    CI_upper = 均值 + 1.96 * 标准误,
    .groups = 'drop')

figba <- ggplot(ba_summary, aes(x = x_pos, y = 均值, fill = 组别)) +
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper),
                position = position_dodge(0.75),
                width = 0.2, color = "grey10", linewidth = 0.6) +
  geom_col(alpha = 0.85, width = 0.70, position = position_dodge(0.75)) +
  geom_point(data = df_unique, 
             aes(x = x_pos, y = 可能性, color = 组别),
             position = position_jitterdodge(jitter.width = 0.08, dodge.width = 0.65),
             size = 2.5, alpha = 0.7, show.legend = FALSE) +
  labs(y = "句法对齐", x = "句法结构", fill = "组别") +
  theme_test() +
  theme(axis.text.x = element_text(size = 12, face = "plain"),
        axis.text.y = element_text(size = 12, face = "plain"),
        axis.title.y = element_text(size = 12, face = "plain"),
        axis.title.x = element_blank(),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_blank(),
        legend.text = element_text(size = 12, face = "plain"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.margin = margin(5, 5, 5, 5)) +
  scale_fill_manual(values = c("TDC" = "#B3742D", "ASD" = "#006654"),
                    labels = c("TDC" = "TD儿童", "ASD" = "ASD儿童")) +
  scale_color_manual(values = c("TDC" = "#B3742D", "ASD" = "#006654")) +
  scale_x_continuous(
    breaks = c(1, 2),
    labels = c("把字句", "主动句"),
    limits = c(0.5, 2.5),
    expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2), 
                     expand = expansion(mult = c(0, 0.05)))
```

```{r 主动句和被动句画图}
dfbe2 <- dfbe0 %>% mutate(x_pos = case_when(句法结构 == "be" ~ 1, 句法结构 == "zh" ~ 2))
df_unique <- dfbe2 %>%distinct(Child_name, 组别, 句法结构, 可能性, .keep_all = TRUE)

be_summary <- df_unique %>%
  group_by(组别, 句法结构, x_pos) %>%
  summarise(
    均值 = mean(可能性),
    标准差 = sd(可能性),
    n = n(),
    标准误 = 标准差 / sqrt(n),
    CI_lower = 均值 - 1.96 * 标准误,
    CI_upper = 均值 + 1.96 * 标准误,
    .groups = 'drop')

figbe <- ggplot(be_summary, aes(x = x_pos, y = 均值, fill = 组别)) +
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper),
                position = position_dodge(0.75),
                width = 0.2, color = "grey10", linewidth = 0.6) +
  geom_col(alpha = 0.85, width = 0.70, position = position_dodge(0.75)) +
  geom_point(data = df_unique, 
             aes(x = x_pos, y = 可能性, color = 组别),
             position = position_jitterdodge(jitter.width = 0.08, dodge.width = 0.65),
             size = 2.5, alpha = 0.7, show.legend = FALSE) +
  labs(y = "句法对齐", x = "句法结构", fill = "组别") +
  theme_test() +
  theme(axis.text.x = element_text(size = 12, face = "plain"),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_blank(),
        legend.text = element_text(size = 12, face = "plain"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_blank(),
        plot.margin = margin(5, 5, 5, 5)) +
  scale_fill_manual(values = c("TDC" = "#B3742D", "ASD" = "#006654"),
                    labels = c("TDC" = "TD儿童", "ASD" = "ASD儿童")) +
  scale_color_manual(values = c("TDC" = "#B3742D", "ASD" = "#006654"),
                     labels = c("TDC" = "TD儿童", "ASD" = "ASD儿童")) +
  scale_x_continuous(
    breaks = c(1, 2),
    labels = c("被字句", "主动句"),
    limits = c(0.5, 2.5),
    expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.2), 
                     expand = expansion(mult = c(0, 0.05)))

babe_plot <- (figba + figbe) + 
  plot_layout(
    guides = "collect",
    nrow = 1,
    widths = c(1, 1)) &
  theme(
    legend.position = "right",
    legend.justification = "center",
    legend.box = "horizontal",
    legend.title = element_blank(),
    legend.text = element_text(size = 11)
  )
print(babe_plot)
ggsave("./figure/babe.svg", plot = babe_plot, width = 6.5, height = 4)
ggsave("./figure/babe.png", plot = babe_plot, width = 6.5, height = 4)
```


```{r 把被联合分析数据整理}
dfba1 <- dfba |>
  group_by(Child_name, Group, Syntax_prime, 词类) |>
  summarise(可能性 = mean(predict)) |>
  ungroup() |>
  dplyr::filter(Syntax_prime == "ba") |>
  as.data.frame() |>
  rename(组别 = Group, 句法结构 = "Syntax_prime")
dfbe1 <- dfbe |>
  group_by(Child_name, Group, Syntax_prime, 词类) |>
  summarise(可能性 = mean(predict)) |>
  ungroup() |>
  dplyr::filter(Syntax_prime == "be") |>
  as.data.frame() |>
  rename(组别 = Group, 句法结构 = "Syntax_prime")
df_hb <- rbind(dfba1, dfbe1) |> dplyr::mutate(可能性 = as.numeric(可能性))
```

```{r 把被联合分析模型建立}
set.seed(0331)
models_lh <- list(
  lh1 = 可能性 ~ 词类 + 句法结构 + 组别 + (1| Child_name),
  lh2 = 可能性 ~ 词类 * 组别 + 句法结构 + (1| Child_name),
  lh3 = 可能性 ~ 词类 * 句法结构 + 组别 + (1| Child_name),
  lh4 = 可能性 ~ 句法结构 * 组别 + 词类 + (1| Child_name),
  lh5 = 可能性 ~ 词类 + 句法结构 + 组别,
  lh6 = 可能性 ~ 词类 * 组别 + 句法结构,
  lh7 = 可能性 ~ 词类 * 句法结构 + 组别,
  lh8 = 可能性 ~ 句法结构 * 组别 + 词类,
  lh9 = 可能性 ~ 句法结构 * 组别 + (1| Child_name),
  lh10 = 可能性 ~ 句法结构 + 组别 + (1| Child_name)
 ) 

lh_objects <- list()
lh_summaries <- list ()
for (model_name in names(models_lh)) {
  formula <- models_lh[[model_name]]
  model <- brm(
    formula = formula,
    data = df_hb,
    family = Beta(link = "logit"),
    init = 0,
    chains = 4,
    warmup = 1000,
    iter = 5000,
    thin = 1,
    cores = 4)

  lh_objects[[model_name]] <- model
  lh_summaries[[model_name]] <- summary(model)
}
```

```{r 联合分析模型比较和拟合}
loo_lh <- list()
for (model_name in names(lh_objects)) {
  loo_lh[[model_name]] <- LOO(lh_objects[[model_name]])
}
lh.compare <- brms::LOO(
  lh_objects$lh1,
  lh_objects$lh2,
  lh_objects$lh3,
  lh_objects$lh4,
  lh_objects$lh5,
  lh_objects$lh6,
  lh_objects$lh7,
  lh_objects$lh8,
  lh_objects$lh9,
  lh_objects$lh10
)

lh1.mae <- posterior_predict(lh_objects$lh1)
lh2.mae <- posterior_predict(lh_objects$lh2)
lh3.mae <- posterior_predict(lh_objects$lh3)
lh4.mae <- posterior_predict(lh_objects$lh4)
lh5.mae <- posterior_predict(lh_objects$lh5)
lh6.mae <- posterior_predict(lh_objects$lh6)
lh7.mae <- posterior_predict(lh_objects$lh7)
lh8.mae <- posterior_predict(lh_objects$lh8)
lh9.mae <- posterior_predict(lh_objects$lh9)
lh10.mae <- posterior_predict(lh_objects$lh10)

lh1 <- median(abs(apply(lh1.mae, 2, mean) - df_hb[, 5]))
lh2 <- median(abs(apply(lh2.mae, 2, mean) - df_hb[, 5]))
lh3 <- median(abs(apply(lh3.mae, 2, mean) - df_hb[, 5]))
lh4 <- median(abs(apply(lh4.mae, 2, mean) - df_hb[, 5]))
lh5 <- median(abs(apply(lh5.mae, 2, mean) - df_hb[, 5]))
lh6 <- median(abs(apply(lh6.mae, 2, mean) - df_hb[, 5]))
lh7 <- median(abs(apply(lh7.mae, 2, mean) - df_hb[, 5]))
lh8 <- median(abs(apply(lh8.mae, 2, mean) - df_hb[, 5]))
lh9 <- median(abs(apply(lh9.mae, 2, mean) - df_hb[, 5]))
lh10 <- median(abs(apply(lh10.mae, 2, mean) - df_hb[, 5]))


chayi_trace <- bayesplot::mcmc_trace(lh_objects$lh3,
                                     pars = c("b_词类结果动补",
                                              "b_句法结构be",
                                              "b_组别ASD",
                                              "b_词类结果动补:句法结构be")) +
  theme(legend.text = element_text(size = 8),
        legend.title = element_text(size = 10),
        legend.margin = margin(1, 1, 1, 1, "pt"),
        legend.key.size = unit(1, "lines"),
        legend.key.height = unit(1, "lines")) +
  guides(color = guide_legend(override.aes = list(size = 0.5)))
chayi_trace
ggsave(plot = chayi_trace, "./figure/chayi_trace.svg", width = 12, height = 4)

chayi.ppcheck <- pp_check(lh_objects$lh3, ndraws = 100)
chayi.ppcheck 
chayi.b <- mcmc_plot(lh_objects$lh3,
                     variable = c("b_词类结果动补",
                                  "b_句法结构be",
                                  "b_组别ASD",
                                  "b_词类结果动补:句法结构be"),
                      type = "areas", prob = 0.95)
chayi.b
chayi.pos <- posterior_predict(lh_objects$lh3)
chayi.hdi <- bayestestR::hdi(lh_objects$lh3)
df_hb$predict = predict(lh_objects$lh3, type = "response")[, 1]
```

```{r 联合分析概率转换}
beta_0 <- 0.62      # Intercept
beta_1 <- 0.75      # 词类结果动补
beta_2 <- -1.89     # 句法结构be
beta_3 <- 0.21      # 组别ASD
beta_4 <- -0.58     # 交互项

inv_logit <- function(x) {
  exp(x) / (1 + exp(x))
}

conditions <- expand.grid(
  组别 = c("TD", "ASD"),
  词类 = c("趋向动补", "结果动补"),
  句法结构 = c("把字句", "be")
)

conditions$logit <- NA
conditions$概率 <- NA

for (i in 1:nrow(conditions)) {
  use_beta1 <- ifelse(conditions$词类[i] == "结果动补", 1, 0)
  use_beta2 <- ifelse(conditions$句法结构[i] == "be", 1, 0)
  use_beta3 <- ifelse(conditions$组别[i] == "ASD", 1, 0)
  use_beta4 <- ifelse(conditions$词类[i] == "结果动补" & conditions$句法结构[i] == "be", 1, 0)
  conditions$logit[i] <- beta_0 + 
                         beta_1 * use_beta1 + 
                         beta_2 * use_beta2 + 
                         beta_3 * use_beta3 + 
                         beta_4 * use_beta4
  conditions$概率[i] <- inv_logit(conditions$logit[i])
}
```



```{r 联合分析柱状图}
df_hb <- df_hb %>%
  mutate(
    x_pos = case_when(
      句法结构 == "ba" & 词类 == "趋向动补" ~ 1,
      句法结构 == "ba" & 词类 == "结果动补" ~ 1.35,
      句法结构 == "be" & 词类 == "趋向动补" ~ 2,
      句法结构 == "be" & 词类 == "结果动补" ~ 2.35))

lh_summary <- df_hb %>%
  group_by(组别, 句法结构, 词类, x_pos) %>%
  summarise(
    均值 = mean(可能性),
    标准差 = sd(可能性),
    n = n(),
    标准误 = 标准差 / sqrt(n),
    CI_lower = 均值 - 1.96 * 标准误,
    CI_upper = 均值 + 1.96 * 标准误,
    .groups = 'drop')
figlh <- ggplot(lh_summary, aes(x = x_pos, y = 均值, fill = 词类)) +
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper),
                position = position_dodge(0.6),
                width = 0.1, color = "grey10", linewidth = 0.6) +
  geom_col(alpha = 0.85, width = 0.3, position = position_dodge(0.6)) +
  geom_point(data = df_hb, 
             aes(x = x_pos, y = 可能性, color = 词类),
             position = position_jitter(width = 0.02, height = 0),
             size = 2.5, alpha = 0.7, show.legend = FALSE) +
  facet_wrap(~组别, nrow = 1,
             labeller = labeller(组别 = c("TDC"="典型儿童","ASD"="孤独症儿童"))) +
  labs(y = "句法对齐可能性", x = "句法结构", fill = "词类") +
  theme_test() +
  theme(
    axis.text.x = element_text(size=12),
    axis.text.y = element_text(size=12),
    axis.title.x = element_blank(),
    strip.text = element_text(size=12),
    legend.title = element_blank(),
    legend.text = element_text(size=12)) +
  scale_fill_manual(values = c("趋向动补"="#B3742D", "结果动补"="#006654"),
                    labels = c("趋向动补"="动趋式","结果动补"="动结式")) +
  scale_color_manual(values = c("趋向动补"="#B3742D", "结果动补"="#006654")) +
  scale_x_continuous(
    breaks = c(1.17, 2.17),
    labels = c("把字句","被字句")) +
  scale_y_continuous(limits = c(0,0.9), breaks = seq(0,0.9,0.2), 
                     expand = expansion(mult = c(0, 0.05)))
figlh
ggsave("./figure/figlh.svg", plot = figlh, width = 6.5, height = 4)
ggsave("./figure/figlh.png", plot = figlh, width = 6.5, height = 4)
```

```{r 被字句时说什么整理}
df02 <- df %>%
  dplyr::filter(Sen_ACC == 1) %>%
  merge(basic, by = "Child_name") %>%
  dplyr::mutate(Group = Group.x) %>%
  dplyr::select(-Group.x, -Group.y, -contains(".x"), -contains(".y"), -Task_Data, -Birth_data) %>%
  dplyr::select(Child_name, Sex, Age, Group, everything()) %>%
  dplyr::mutate(词类 = ifelse(Words_prime %in% quxiang, "趋向动补", "结果动补"),
                词类 = factor(词类, levels = c("趋向动补", "结果动补")),
                Syntax_production = ifelse(is.na(Syntax_production), "错误",
                                           as.character(Syntax_production)),
                Group = factor(Group, levels = c("TDC", "ASD")),
                Syntax_prime = factor(Syntax_prime, levels = c("zh", "ba", "be")))
df02 <- merge(df02, pingfen, by = "Rate_ID")
```

```{r 被字句时说什么贝叶斯}
dfbe3 <- df02 |>
  dplyr::select(Child_name, Group, Syntax_prime, Syntax_production, PPVTZ, 词类, Trials) |>
  dplyr::filter(Syntax_prime == "be", Syntax_production != "错误") |>
  dplyr::mutate(Syntax_production = factor(Syntax_production, levels = c("be", "ba", "zh")))
set.seed(326)
model_formulas <- list(
  mul.be1 = Syntax_production ~ 1 + Group * 词类 + (1| Child_name) + (1 | Trials),
  mul.be2 = Syntax_production ~ 1 + Group + 词类 + (1| Child_name) + (1 | Trials),
  mul.be3 = Syntax_production ~ 1 + Group * 词类 + (1| Trials),
  mul.be4 = Syntax_production ~ 1 + Group + 词类 + (1| Trials),
  mul.be5 = Syntax_production ~ 1 + Group * 词类 + (1| Child_name),
  mul.be6 = Syntax_production ~ 1 + Group + 词类 + (1| Child_name),
  mul.be7 = Syntax_production ~ 1 + Group * 词类,
  mul.be8 = Syntax_production ~ 1 + Group + 词类,
  mul.be9 = Syntax_production ~ 1 + Group + (1| Trials) +(1| Child_name),
  mul.be10 = Syntax_production ~ 1 + Group + (1| Trials),
  mul.be11 = Syntax_production ~ 1 + Group + (1| Child_name),
  mul.be12 = Syntax_production ~ 1 + Group,
  mul.be13 = Syntax_production ~ 1 + 词类 + (1| Child_name) + (1 | Trials),
  mul.be14 = Syntax_production ~ 1 + 词类 + (1| Child_name),
  mul.be15 = Syntax_production ~ 1 + 词类 + (1| Trials),
  mul.be16 = Syntax_production ~ 1 + 词类,
  mul.be17 = Syntax_production ~ 1) 

BE_objects <- list()
BE_summaries <- list ()
for (model_name in names(model_formulas)) {
  formula <- model_formulas[[model_name]]
  model <- brm(
    formula = formula,
    data = dfbe3,
    init = 0,
    family = categorical(link = "logit"),
    chains = 4,
    warmup = 1000,
    iter = 5000,
    thin = 1,
    cores = 4)

  BE_objects[[model_name]] <- model
  BE_summaries[[model_name]] <- summary(model)
}
loo_be <- list()
for (model_name in names(BE_objects)) {
  loo_be[[model_name]] <- LOO(BE_objects[[model_name]])
}
be.compare <- brms::LOO(
  BE_objects$mul.be1,
  BE_objects$mul.be2,
  BE_objects$mul.be3,
  BE_objects$mul.be4,
  BE_objects$mul.be5,
  BE_objects$mul.be6,
  BE_objects$mul.be7,
  BE_objects$mul.be8,
  BE_objects$mul.be9,
  BE_objects$mul.be10,
  BE_objects$mul.be11,
  BE_objects$mul.be12,
  BE_objects$mul.be13,
  BE_objects$mul.be14,
  BE_objects$mul.be15,
  BE_objects$mul.be16,
  BE_objects$mul.be17
)
BE.hdi <- bayestestR::hdi(BE_objects$mul.be9)
BE_objects$mul.be9
```

```{r 被字句概率转换}
#TD儿童
rba_be <- exp(summary(BE_objects$mul.be9)$fixed[1,1])
rzh_be <- exp(summary(BE_objects$mul.be9)$fixed[2,1])
# P(be)+P(ba)+P(zh)=1
# P(ba)=rba_be *P(be)
# P(ba)=rzh_be *P(be)
# p(be) = 1/(rba_be + rzh_be) = 0.2455
# p(ba) = 2.53 × 0.2455 = 0.621
# P(zh) = 0.543 × 0.2455 = 0.133
cat("TD儿童产出把字句和被字句的可能性比值是：0.621/0.246", "\n")
#ASD 
Rba_be <- exp(summary(BE_objects$mul.be9)$fixed[1,1] + summary(BE_objects$mul.be9)$fixed[3,1])
Rzh_be <- exp(summary(BE_objects$mul.be9)$fixed[2,1] + summary(BE_objects$mul.be9)$fixed[4,1])
# p(be) = 1 / (1 + Rba_be + Rzh_be)
# P(ba)=1.632×0.3088=0.504
# P(zh)=0.6065×0.3088=0.187
cat("TD儿童产出把字句和被字句的可能性比值是：0.504/0.30831", "\n")
```


```{r 把字句时说什么贝叶斯}
dfba3 <- df02 |>
  dplyr::select(Child_name, Group, Syntax_prime, Syntax_production, PPVTZ, 词类, Trials) |>
  dplyr::filter(Syntax_prime == "ba", 
                Syntax_production != "错误", 
                !is.na(Syntax_production)) |>
  dplyr::mutate(Syntax_production = factor(Syntax_production, levels = c("ba", "be", "zh")))

model_formulas <- list(
  mul.ba1 = Syntax_production ~ 1 + Group * 词类 + (1| Child_name) + (1 | Trials),
  mul.ba2 = Syntax_production ~ 1 + Group + 词类 + (1| Child_name) + (1 | Trials),
  mul.ba3 = Syntax_production ~ 1 + Group * 词类 + (1| Trials),
  mul.ba4 = Syntax_production ~ 1 + Group + 词类 + (1| Trials),
  mul.ba5 = Syntax_production ~ 1 + Group * 词类 + (1| Child_name),
  mul.ba6 = Syntax_production ~ 1 + Group + 词类 + (1| Child_name),
  mul.ba7 = Syntax_production ~ 1 + Group * 词类,
  mul.ba8 = Syntax_production ~ 1 + Group + 词类,
  mul.ba9 = Syntax_production ~ 1 + Group + (1| Trials) +(1| Child_name),
  mul.ba10 = Syntax_production ~ 1 + Group + (1| Trials),
  mul.ba11 = Syntax_production ~ 1 + Group + (1| Child_name),
  mul.ba12 = Syntax_production ~ 1 + Group,
  mul.ba13 = Syntax_production ~ 1 + 词类 + (1| Child_name) + (1 | Trials),
  mul.ba14 = Syntax_production ~ 1 + 词类 + (1| Child_name),
  mul.ba15 = Syntax_production ~ 1 + 词类 + (1| Trials),
  mul.ba16 = Syntax_production ~ 1 + 词类,
  mul.ba17 = Syntax_production ~ 1) 

BA_objects <- list()
BA_summaries <- list ()
for (model_name in names(model_formulas)) {
  formula <- model_formulas[[model_name]]
  model <- brm(
    formula = formula,
    data = dfba3,
    init = 0,
    family = categorical(link = "logit"),
    chains = 4,
    warmup = 1000,
    iter = 5000,
    thin = 1,
    cores = 4)

  BA_objects[[model_name]] <- model
  BA_summaries[[model_name]] <- summary(model)
}
loo_ba <- list()
for (model_name in names(BA_objects)) {
  loo_ba[[model_name]] <- LOO(BA_objects[[model_name]])
}
ba.compare <- brms::LOO(
  BA_objects$mul.ba1,
  BA_objects$mul.ba2,
  BA_objects$mul.ba3,
  BA_objects$mul.ba4,
  BA_objects$mul.ba5,
  BA_objects$mul.ba6,
  BA_objects$mul.ba7,
  BA_objects$mul.ba8,
  BA_objects$mul.ba9,
  BA_objects$mul.ba10,
  BA_objects$mul.ba11,
  BA_objects$mul.ba12,
  BA_objects$mul.ba13,
  BA_objects$mul.ba14,
  BA_objects$mul.ba15,
  BA_objects$mul.ba16,
  BA_objects$mul.ba17
)
BA_objects$mul.ba13
bayestestR::hdi(BA_objects$mul.ba13)
```


```{r 桑基图数据整理}
dfbe4 <- df02 |>
  dplyr::select(Child_name, Group, Syntax_prime, Syntax_production, Syntax_ACC) |>
  dplyr::filter(Syntax_prime == "be", Syntax_production != "gei") |>
  count(Syntax_production, Group) |>
  dplyr::mutate(Syntax_prime = rep("be", 6)) |>
  rename(freq = n)

dfba4 <- df02 |>
  dplyr::select(Child_name, Group, Syntax_prime, Syntax_production, Syntax_ACC, 词类) |>
  dplyr::filter(Syntax_prime == "zh") |>
  count(Syntax_production, Group) |>
  dplyr::mutate(Syntax_prime = rep("ba", 5)) |>
  rename(freq = n)
```

```{r 被字句桑基图}
dfbe4_pct <- dfbe4 %>% mutate(total_all = sum(freq))
right_labels <- data.frame(
  Syntax_production = c("be", "zh", "ba"),
  freq = c(42, 41, 75),
  label = c("被字句\n26.58%", "主动句\n25.95%", "把字句\n47.47%"),
  x = 1.86,
  y = c(21, 62.5, 119))
left_labels <- data.frame(
  Group = c("典型儿童", "孤独症儿童"),
  total = c(81, 78),
  x = 1,
  y = c(85/2, 81 + 78/2)  # TDC在上，ASD在下，调整到中心
) %>%
  mutate(label = paste0(Group, "\n", total))

fig1 <- ggplot(dfbe4_pct, 
               aes(axis1 = Group, 
                   axis2 = Syntax_production, 
                   y = freq)) +
  geom_alluvium(aes(fill = Syntax_production), 
                width = 1/8, 
                alpha = 0.7,
                curve_type = "sigmoid") +
  geom_stratum(width = 1/4, 
               fill = "transparent", 
               color = "grey30", 
               size = 0.5) +
  geom_text(data = left_labels,
            aes(x = x, y = y, label = label),
            inherit.aes = FALSE,
            size = 5) +
  geom_text(data = right_labels,
            aes(x = x, y = y, label = label),
            inherit.aes = FALSE,
            size = 5,
            hjust = 0,
            nudge_x = 0.08) +
  scale_x_discrete(limits = c("被字句", "儿童对齐"), 
                   expand = c(0.15, 0.1),
                   position = "top") +  # 轴标签移到顶部
  scale_fill_manual(values = c("zh" = "#B3742D", 
                               "ba" = "#006654", 
                               "be" = "#7570B3"),
                    name = "产出句法",
                    labels = c("主动句", "把字句", "被字句")) +
  theme_void() +
  theme(legend.position = c(0.5, 1.045),  # x=0.5居中, y=1.05在图上方
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(size = 13),
        legend.key.size = unit(0.6, "cm"),
        axis.text.x = element_text(size = 13, vjust = 2.5),
        axis.title.x = element_blank(),
        plot.margin = margin(t = 10, b = 0, l = 0, r = 0))
fig1
```

```{r 把字句桑基图}
dfba4_pct <- dfba4 %>% mutate(total_all = sum(freq))
right_labels <- data.frame(
  Syntax_production = c("be", "zh", "ba"),
  freq = c(1, 44, 116),
  label = c("被字句\n0.01%", "主动句\n72.05%", "把字句\n27.33%"),
  x = 1.86,
  y = c(105, 65, 140))

left_labels <- data.frame(
  Group = c("典型儿童", "孤独症儿童"),
  total = c(81, 78),
  x = 1,
  y = c(85/2, 81 + 78/2)) %>%
  mutate(label = paste0(Group, "\n", total))

fig2 <- ggplot(dfba4_pct, 
               aes(axis1 = Group, 
                   axis2 = Syntax_production, 
                   y = freq)) +
  geom_alluvium(aes(fill = Syntax_production), 
                width = 1/8, 
                alpha = 0.7,
                curve_type = "sigmoid") +
  geom_stratum(width = 1/4, 
               fill = "transparent", 
               color = "grey30", 
               size = 0.5) +
  geom_text(data = left_labels,
            aes(x = x, y = y, label = label),
            inherit.aes = FALSE,
            size = 5) +
  geom_text(data = right_labels,
            aes(x = x, y = y, label = label),
            inherit.aes = FALSE,
            size = 5,
            hjust = 0,
            nudge_x = 0.08) +
  scale_x_discrete(limits = c("把字句", "儿童对齐"), 
                   expand = c(0.15, 0.1),
                   position = "top") +  # 轴标签移到顶部
  scale_fill_manual(values = c("zh" = "#B3742D", 
                               "ba" = "#006654", 
                               "be" = "#7570B3"),
                    name = "产出句法",
                    labels = c("把字句", "主动句", "被字句")) +
  theme_void() +
  theme(
  legend.position = c(0.5, 1.045),  # x=0.5居中, y=1.05在图上方
  legend.direction = "horizontal",
  legend.title = element_blank(),
  legend.text = element_text(size = 13),
  legend.key.size = unit(0.6, "cm"),
  axis.text.x = element_text(size = 13, vjust = 2.5),
  axis.title.x = element_blank(),
  plot.margin = margin(t = 10, b = 0, l = 0, r = 0)
)
fig2
```

```{r 结果动补+趋向动补}
fig4 <- fig1+fig2
ggsave("./figure/fig4.svg", plot = fig4, width = 12.5, height = 4)
ggsave("./figure/fig4.png", plot = fig4, width = 12.5, height = 4)
```

```{r 评分数据整理}
pingfen <- df01 |>
  dplyr::select(Child_name, Group, Syntax_production, 
                Rating.mean, 词类, Trials, PPVTZ) |>
  group_by(Child_name, Group, Syntax_production, 词类)|>
  summarise(mean = mean(Rating.mean))
```

```{r 产出句法评分}
set.seed(330)
df01$Syntax_production <- factor(df01$Syntax_production, levels = c("be", "ba", "zh"))
model_formulas <- list(
  p1 = Rating.mean ~ 1 + Group * 词类 * Syntax_production + (1| Child_name) + (1 | Trials),
  p2 = Rating.mean ~ 1 + Group * 词类 + Syntax_production + (1| Child_name) + (1 | Trials),
  p3 = Rating.mean ~ 1 + Group + 词类 * Syntax_production + (1| Child_name) + (1 | Trials),
  p4 = Rating.mean ~ 1 + Group + 词类 + Syntax_production + (1| Child_name) + (1 | Trials),
  p5 = Rating.mean ~ 1 + Group * 词类 * Syntax_production + (1| Child_name),
  p6 = Rating.mean ~ 1 + Group * 词类 + Syntax_production + (1| Child_name),
  p7 = Rating.mean ~ 1 + Group + 词类 * Syntax_production + (1| Child_name),
  p8 = Rating.mean ~ 1 + Group + 词类 + Syntax_production + (1| Child_name),
  p9 = Rating.mean ~ 1 + Group * 词类 * Syntax_production + (1 | Trials),
  p10 = Rating.mean ~ 1 + Group * 词类 + Syntax_production + (1 | Trials),
  p11 = Rating.mean ~ 1 + Group + 词类 * Syntax_production + (1 | Trials),
  p12 = Rating.mean ~ 1 + Group + 词类 + Syntax_production + (1 | Trials),
  p13 = Rating.mean ~ 1 + Group * 词类 * Syntax_production,
  p14 = Rating.mean ~ 1 + Group * 词类 + Syntax_production,
  p15 = Rating.mean ~ 1 + Group + 词类 * Syntax_production,
  p16 = Rating.mean ~ 1 + Group + 词类 + Syntax_production) 

p_objects <- list()
p_summaries <- list ()
for (model_name in names(model_formulas)) {
  formula <- model_formulas[[model_name]]
  model <- brm(
    formula = formula,
    data = df01 ,
    init = 0,
    chains = 4,
    warmup = 1000,
    iter = 5000,
    thin = 1,
    cores = 4)

  p_objects[[model_name]] <- model
  p_summaries[[model_name]] <- summary(model)
}
loo_p <- list()
for (model_name in names(p_objects)) {
  loo_p[[model_name]] <- LOO(p_objects[[model_name]])
}
p.compare <- brms::LOO(
  p_objects$p1,
  p_objects$p2,
  p_objects$p3,
  p_objects$p4,
  p_objects$p5,
  p_objects$p6,
  p_objects$p7,
  p_objects$p8,
  p_objects$p9,
  p_objects$p10,
  p_objects$p11,
  p_objects$p12,
  p_objects$p13,
  p_objects$p14,
  p_objects$p15,
  p_objects$p16
)
bayestestR::hdi(p_objects$p3)

p1.mae <- posterior_predict(p_objects$p1)
p2.mae <- posterior_predict(p_objects$p2)
p3.mae <- posterior_predict(p_objects$p3)
p4.mae <- posterior_predict(p_objects$p4)
p5.mae <- posterior_predict(p_objects$p5)
p6.mae <- posterior_predict(p_objects$p6)
p7.mae <- posterior_predict(p_objects$p7)
p8.mae <- posterior_predict(p_objects$p8)
p9.mae <- posterior_predict(p_objects$p9)
p10.mae <- posterior_predict(p_objects$p10)
p11.mae <- posterior_predict(p_objects$p11)
p12.mae <- posterior_predict(p_objects$p12)
p13.mae <- posterior_predict(p_objects$p13)
p14.mae <- posterior_predict(p_objects$p14)
p15.mae <- posterior_predict(p_objects$p15)
p16.mae <- posterior_predict(p_objects$p16)

p1 <- median(abs(apply(p1.mae, 2, mean) - df01[, 27]))
p2 <- median(abs(apply(p2.mae, 2, mean) - df01[, 27]))
p3 <- median(abs(apply(p3.mae, 2, mean) - df01[, 27]))
p4 <- median(abs(apply(p4.mae, 2, mean) - df01[, 27]))
p5 <- median(abs(apply(p5.mae, 2, mean) - df01[, 27]))
p6 <- median(abs(apply(p6.mae, 2, mean) - df01[, 27]))
p7 <- median(abs(apply(p7.mae, 2, mean) - df01[, 27]))
p8 <- median(abs(apply(p8.mae, 2, mean) - df01[, 27]))
p9 <- median(abs(apply(p9.mae, 2, mean) - df01[, 27]))
p10 <- median(abs(apply(p10.mae, 2, mean) - df01[, 27]))
p11 <- median(abs(apply(p11.mae, 2, mean) - df01[, 27]))
p12 <- median(abs(apply(p12.mae, 2, mean) - df01[, 27]))
p13 <- median(abs(apply(p13.mae, 2, mean) - df01[, 27]))
p14 <- median(abs(apply(p14.mae, 2, mean) - df01[, 27]))
p15 <- median(abs(apply(p15.mae, 2, mean) - df01[, 27]))
p16 <- median(abs(apply(p16.mae, 2, mean) - df01[, 27]))

p.result <- paste0("p", 1:16)
for (v in p.result) {
  print(head(get(v)))
}
```





########################################################################

```{r 诱发句法评分}
model_formulas <- list(
  y1 = Rating.mean ~ 1 + Group * 词类 * Syntax_prime + (1| Child_name) + (1 | Trials),
  y2 = Rating.mean ~ 1 + Group * 词类 + Syntax_prime + (1| Child_name) + (1 | Trials),
  y3 = Rating.mean ~ 1 + Group + 词类 * Syntax_prime + (1| Child_name) + (1 | Trials),
  y4 = Rating.mean ~ 1 + Group + 词类 + Syntax_prime + (1| Child_name) + (1 | Trials),
  y5 = Rating.mean ~ 1 + Group * 词类 * Syntax_prime + (1| Child_name),
  y6 = Rating.mean ~ 1 + Group * 词类 + Syntax_prime + (1| Child_name),
  y7 = Rating.mean ~ 1 + Group + 词类 * Syntax_prime + (1| Child_name),
  y8 = Rating.mean ~ 1 + Group + 词类 + Syntax_prime + (1| Child_name),
  y9 = Rating.mean ~ 1 + Group * 词类 * Syntax_prime + (1 | Trials),
  y10 = Rating.mean ~ 1 + Group * 词类 + Syntax_prime + (1 | Trials),
  y11 = Rating.mean ~ 1 + Group + 词类 * Syntax_prime + (1 | Trials),
  y12 = Rating.mean ~ 1 + Group + 词类 + Syntax_prime + (1 | Trials),
  y13 = Rating.mean ~ 1 + Group * 词类 * Syntax_prime,
  y14 = Rating.mean ~ 1 + Group * 词类 + Syntax_prime,
  y15 = Rating.mean ~ 1 + Group + 词类 * Syntax_prime,
  y16 = Rating.mean ~ 1 + Group + 词类 + Syntax_prime,
  y17 = Rating.mean ~ 1 + Group * 词类 + (1| Trials) +(1| Child_name),
  y18 = Rating.mean ~ 1 + Group * 词类 + (1| Trials),
  y19 = Rating.mean ~ 1 + Group * 词类+ (1| Child_name),
  y20 = Rating.mean ~ 1 + Group * 词类,
  y21 = Rating.mean ~ 1 + Group * Syntax_prime + (1| Trials) +(1| Child_name),
  y22 = Rating.mean ~ 1 + Group * Syntax_prime + (1| Trials),
  y23 = Rating.mean ~ 1 + Group * Syntax_prime + (1| Child_name),
  y24 = Rating.mean ~ 1 + Group * Syntax_prime,
  y25 = Rating.mean ~ 1 + Group + 词类 + (1| Trials) +(1| Child_name),
  y26 = Rating.mean ~ 1 + Group + 词类 + (1| Trials),
  y27 = Rating.mean ~ 1 + Group + 词类+ (1| Child_name),
  y28 = Rating.mean ~ 1 + Group + 词类,
  y29 = Rating.mean ~ 1 + Group + Syntax_prime + (1| Trials) +(1| Child_name),
  y30 = Rating.mean ~ 1 + Group + Syntax_prime + (1| Trials),
  y31 = Rating.mean ~ 1 + Group + Syntax_prime + (1| Child_name),
  y32 = Rating.mean ~ 1 + Group + Syntax_prime,
  y33 = Rating.mean ~ 1 + Syntax_prime * 词类 + (1| Trials) +(1| Child_name),
  y34 = Rating.mean ~ 1 + Syntax_prime * 词类 + (1| Trials),
  y35 = Rating.mean ~ 1 + Syntax_prime * 词类+ (1| Child_name),
  y36 = Rating.mean ~ 1 + Syntax_prime * 词类,
  y37 = Rating.mean ~ 1 + Syntax_prime + 词类 + (1| Trials) +(1| Child_name),
  y38 = Rating.mean ~ 1 + Syntax_prime + 词类 + (1| Trials),
  y39 = Rating.mean ~ 1 + Syntax_prime + 词类+ (1| Child_name),
  y40 = Rating.mean ~ 1 + Syntax_prime + 词类,
  y41 = Rating.mean ~ 1 + 词类 + (1| Trials) +(1| Child_name),
  y42 = Rating.mean ~ 1 + 词类 + (1| Trials),
  y43 = Rating.mean ~ 1 + 词类 + (1| Child_name),
  y44 = Rating.mean ~ 1 + 词类,
  y45 = Rating.mean ~ 1 + Group + (1| Trials) +(1| Child_name),
  y46 = Rating.mean ~ 1 + Group + (1| Trials),
  y47 = Rating.mean ~ 1 + Group+ (1| Child_name),
  y48 = Rating.mean ~ 1 + Group,
  y49 = Rating.mean ~ 1 + Syntax_prime + (1| Trials) +(1| Child_name),
  y50 = Rating.mean ~ 1 + Syntax_prime + (1| Trials),
  y51 = Rating.mean ~ 1 + Syntax_prime+ (1| Child_name),
  y52 = Rating.mean ~ 1 + Syntax_prime
  ) 

y_objects <- list()
y_summaries <- list ()
for (model_name in names(model_formulas)) {
  formula <- model_formulas[[model_name]]
  model <- brm(
    formula = formula,
    data = df01 ,
    init = 0,
    chains = 4,
    warmup = 1000,
    iter = 5000,
    thin = 1,
    cores = 4)

  y_objects[[model_name]] <- model
  y_summaries[[model_name]] <- summary(model)
}
loo_y <- list()
for (model_name in names(y_objects)) {
  loo_y[[model_name]] <- LOO(y_objects[[model_name]])
}
y.compare <- brms::LOO(
  y_objects$y1,
  y_objects$y2,
  y_objects$y3,
  y_objects$y4,
  y_objects$y5,
  y_objects$y6,
  y_objects$y7,
  y_objects$y8,
  y_objects$y9,
  y_objects$y10,
  y_objects$y11,
  y_objects$y12,
  y_objects$y13,
  y_objects$y14,
  y_objects$y15,
  y_objects$y16,
  y_objects$y17,
  y_objects$y18,
  y_objects$y19,
  y_objects$y20,
  y_objects$y21,
  y_objects$y22,
  y_objects$y23,
  y_objects$y24,
  y_objects$y25,
  y_objects$y26,
  y_objects$y27,
  y_objects$y28,
  y_objects$y29,
  y_objects$y30,
  y_objects$p31,
  y_objects$p32,
  y_objects$p33,
  y_objects$p34,
  y_objects$p35,
  y_objects$p36,
  y_objects$p37,
  y_objects$p38,
  y_objects$p39,
  y_objects$p30,
  y_objects$p41,
  y_objects$p42,
  y_objects$p43,
  y_objects$p44,
  y_objects$p45,
  y_objects$p46,
  y_objects$p47,
  y_objects$p48,
  y_objects$p49,
  y_objects$p40,
  y_objects$p51,
  y_objects$p52
)
bayestestR::hdi(y_objects$y25)

y1.mae <- posterior_predict(y_objects$y1)
y2.mae <- posterior_predict(y_objects$y2)
y3.mae <- posterior_predict(y_objects$y3)
y4.mae <- posterior_predict(y_objects$y4)
y5.mae <- posterior_predict(y_objects$y5)
y6.mae <- posterior_predict(y_objects$y6)
y7.mae <- posterior_predict(y_objects$y7)
y8.mae <- posterior_predict(y_objects$y8)
y9.mae <- posterior_predict(y_objects$y9)
y10.mae <- posterior_predict(y_objects$y10)
y11.mae <- posterior_predict(y_objects$y11)
y12.mae <- posterior_predict(y_objects$y12)
y13.mae <- posterior_predict(y_objects$y13)
y14.mae <- posterior_predict(y_objects$y14)
y15.mae <- posterior_predict(y_objects$y15)
y16.mae <- posterior_predict(y_objects$y16)
y17.mae <- posterior_predict(y_objects$y17)
y18.mae <- posterior_predict(y_objects$y18)
y19.mae <- posterior_predict(y_objects$y19)
y20.mae <- posterior_predict(y_objects$y20)
y21.mae <- posterior_predict(y_objects$y21)
y22.mae <- posterior_predict(y_objects$y22)
y23.mae <- posterior_predict(y_objects$y23)
y24.mae <- posterior_predict(y_objects$y24)
y25.mae <- posterior_predict(y_objects$y25)
y26.mae <- posterior_predict(y_objects$y26)
y27.mae <- posterior_predict(y_objects$y27)
y28.mae <- posterior_predict(y_objects$y28)
y29.mae <- posterior_predict(y_objects$y29)
y30.mae <- posterior_predict(y_objects$y30)
y31.mae <- posterior_predict(y_objects$y31)
y32.mae <- posterior_predict(y_objects$y32)
y33.mae <- posterior_predict(y_objects$y33)
y34.mae <- posterior_predict(y_objects$y34)
y35.mae <- posterior_predict(y_objects$y35)
y36.mae <- posterior_predict(y_objects$y36)
y37.mae <- posterior_predict(y_objects$y37)
y38.mae <- posterior_predict(y_objects$y38)
y39.mae <- posterior_predict(y_objects$y39)
y40.mae <- posterior_predict(y_objects$y40)
y41.mae <- posterior_predict(y_objects$y41)
y42.mae <- posterior_predict(y_objects$y42)
y43.mae <- posterior_predict(y_objects$y43)
y44.mae <- posterior_predict(y_objects$y44)
y45.mae <- posterior_predict(y_objects$y45)
y46.mae <- posterior_predict(y_objects$y46)
y47.mae <- posterior_predict(y_objects$y47)
y48.mae <- posterior_predict(y_objects$y48)
y49.mae <- posterior_predict(y_objects$y49)
y50.mae <- posterior_predict(y_objects$y50)
y51.mae <- posterior_predict(y_objects$y51)
y52.mae <- posterior_predict(y_objects$y52)

y1 <- median(abs(apply(y1.mae, 2, mean) - df01[, 27]))
y2 <- median(abs(apply(y2.mae, 2, mean) - df01[, 27]))
y3 <- median(abs(apply(y3.mae, 2, mean) - df01[, 27]))
y4 <- median(abs(apply(y4.mae, 2, mean) - df01[, 27]))
y5 <- median(abs(apply(y5.mae, 2, mean) - df01[, 27]))
y6 <- median(abs(apply(y6.mae, 2, mean) - df01[, 27]))
y7 <- median(abs(apply(y7.mae, 2, mean) - df01[, 27]))
y8 <- median(abs(apply(y8.mae, 2, mean) - df01[, 27]))
y9 <- median(abs(apply(y9.mae, 2, mean) - df01[, 27]))
y10 <- median(abs(apply(y10.mae, 2, mean) - df01[, 27]))
y11 <- median(abs(apply(y11.mae, 2, mean) - df01[, 27]))
y12 <- median(abs(apply(y12.mae, 2, mean) - df01[, 27]))
y13 <- median(abs(apply(y13.mae, 2, mean) - df01[, 27]))
y14 <- median(abs(apply(y14.mae, 2, mean) - df01[, 27]))
y15 <- median(abs(apply(y15.mae, 2, mean) - df01[, 27]))
y16 <- median(abs(apply(y16.mae, 2, mean) - df01[, 27]))
y17 <- median(abs(apply(y17.mae, 2, mean) - df01[, 27]))
y18 <- median(abs(apply(y18.mae, 2, mean) - df01[, 27]))
y19 <- median(abs(apply(y19.mae, 2, mean) - df01[, 27]))
y20 <- median(abs(apply(y20.mae, 2, mean) - df01[, 27]))
y21 <- median(abs(apply(y21.mae, 2, mean) - df01[, 27]))
y22 <- median(abs(apply(y22.mae, 2, mean) - df01[, 27]))
y23 <- median(abs(apply(y23.mae, 2, mean) - df01[, 27]))
y24 <- median(abs(apply(y24.mae, 2, mean) - df01[, 27]))
y25 <- median(abs(apply(y25.mae, 2, mean) - df01[, 27]))
y26 <- median(abs(apply(y26.mae, 2, mean) - df01[, 27]))
y27 <- median(abs(apply(y27.mae, 2, mean) - df01[, 27]))
y28 <- median(abs(apply(y28.mae, 2, mean) - df01[, 27]))
y29 <- median(abs(apply(y29.mae, 2, mean) - df01[, 27]))
y30 <- median(abs(apply(y30.mae, 2, mean) - df01[, 27]))
y31 <- median(abs(apply(y31.mae, 2, mean) - df01[, 27]))
y32 <- median(abs(apply(y32.mae, 2, mean) - df01[, 27]))
y33 <- median(abs(apply(y33.mae, 2, mean) - df01[, 27]))
y34 <- median(abs(apply(y34.mae, 2, mean) - df01[, 27]))
y35 <- median(abs(apply(y35.mae, 2, mean) - df01[, 27]))
y36 <- median(abs(apply(y36.mae, 2, mean) - df01[, 27]))
y37 <- median(abs(apply(y37.mae, 2, mean) - df01[, 27]))
y38 <- median(abs(apply(y38.mae, 2, mean) - df01[, 27]))
y39 <- median(abs(apply(y39.mae, 2, mean) - df01[, 27]))
y40 <- median(abs(apply(y30.mae, 2, mean) - df01[, 27]))
y41 <- median(abs(apply(y41.mae, 2, mean) - df01[, 27]))
y42 <- median(abs(apply(y42.mae, 2, mean) - df01[, 27]))
y43 <- median(abs(apply(y43.mae, 2, mean) - df01[, 27]))
y44 <- median(abs(apply(y44.mae, 2, mean) - df01[, 27]))
y45 <- median(abs(apply(y45.mae, 2, mean) - df01[, 27]))
y46 <- median(abs(apply(y46.mae, 2, mean) - df01[, 27]))
y47 <- median(abs(apply(y47.mae, 2, mean) - df01[, 27]))
y48 <- median(abs(apply(y48.mae, 2, mean) - df01[, 27]))
y49 <- median(abs(apply(y49.mae, 2, mean) - df01[, 27]))
y50 <- median(abs(apply(y50.mae, 2, mean) - df01[, 27]))
y51 <- median(abs(apply(y51.mae, 2, mean) - df01[, 27]))
y52 <- median(abs(apply(y52.mae, 2, mean) - df01[, 27]))

y.result <- paste0("y", 1:52)
for (v in y.result) {
  print(head(get(v)))
}
```


```{r 评分fig4}
pf_new <- df01 %>% 
  dplyr::select(Syntax_prime, Syntax_production, Rating.mean, 词类, Group, Words_prime) |>
  dplyr::group_by(Words_prime, 词类, Group) |>
  dplyr::summarise(
    pingfen = mean(Rating.mean, na.rm = TRUE), .groups = "drop")|>
  arrange(词类, pingfen)|>
  dplyr::mutate(Words_prime = factor(Words_prime, levels = unique(Words_prime))) |>
  pivot_wider(names_from = Group, values_from = pingfen)
table(pf_new$词类)
n_quxiang <- sum(pf_new$词类 == "趋向动补")
fig4 <- ggplot(pf_new) +
  annotate("rect", xmin = n_quxiang + 0.5, xmax = Inf,
           ymin = -Inf, ymax = Inf, fill = "grey90", alpha = 0.5) +
  annotate("rect", xmin = -Inf, xmax = n_quxiang + 0.5,
           ymin = -Inf, ymax = Inf, fill = "white", alpha = 0.3) +
  geom_segment(aes(x = Words_prime, xend = Words_prime, y = ASD, yend = TDC),
               size = 1.5, color = "grey40") +
  geom_point(aes(x = Words_prime, y = ASD), 
             size = 4, color = "#B3742D", fill = "#B3742D", shape = 21) +
  geom_point(aes(x = Words_prime, y = TDC), 
             size = 4, color = "#006654", fill = "#006654", shape = 21) +
  annotate("point", x = 8, y = 10.2, size = 4, 
           color = "#B3742D", fill = "#B3742D", shape = 21) +
  annotate("text", x = 8, y = 10.3, label = "孤独症儿童", 
           size = 3.5, hjust = 0) +
  annotate("point", x = 7, y = 10.2, size = 4, 
           color = "#006654", fill = "#006654", shape = 21) +
  annotate("text", x = 7, y = 10.3, label = "典型儿童", 
           size = 3.5, hjust = 0) +
  annotate("rect", xmin = 8.75, xmax = 9.25, ymin = 10.14, ymax = 10.26, 
           fill = "grey90", color = "grey60", size = 0.3) +
  annotate("text", x = 9, y = 10.3, label = "结果动补", 
           size = 3.5, hjust = 0) +
  annotate("rect", xmin = 5.75, xmax = 6.25, ymin = 10.14, ymax = 10.26, 
           fill = "white", color = "grey60", size = 0.3) +
  annotate("text", x = 6, y = 10.3, label = "趋向动补", 
           size = 3.5, hjust = 0) +
  theme_test() +
  labs(y = NULL, x = NULL) +
  coord_flip(ylim = c(5, 11)) + 
  theme(axis.text.x = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 12, color = "black"),
        axis.ticks.y = element_blank(), 
        panel.grid.major = element_line(size = 0.2, color = "#e5e5e5"))
fig4
ggsave("./figure/fig4.svg", plot = fig4, width = 7, height = 5)
ggsave("./figure/fig4.png", plot = fig4, width = 7, height = 5)
```



###############################################################################################
